// src/app/views/Character/CharSkills/Skills/Skills.tsx
import { useSelector } from "react-redux"
import { ChangeEvent, useState } from "react"
import { RootState, useAppDispatch, useAppSelector } from "../../../../redux"
import Input from "../../../../components/Input/Input"
import styles from "./Skills.module.scss"
import { addSkill } from "../../../../redux/slices/charSlice"
export const CharSkills = () => {
    const asyncDispatch = useAppDispatch()
    const { char, modifiers, skills } = useAppSelector((state: RootState) => state.character.selectedChar)
    const token = useAppSelector((state: RootState) => state.token.token)
    const [charSkills, setCharSkills] = useState(char.Skills?.map((sk: Skill) => sk.name))
    const [possibleCharSkillProf] = useState(char.Class?.skillProf.map((sk: Skill) => sk.name))
    const chooseSkill = (name: string) => {
        if (possibleCharSkillProf.includes(name)) {
            asyncDispatch(addSkill({ token, id: char.id, skillName: name }))
        }
    }
    return <>
        <form className={styles["skill__form"]}>
            You still have {char.skillProfLeft} skills to add to your profs
            {skills?.map((sk: Skill) => <label className={possibleCharSkillProf.includes(sk.name) ? styles["skill__prof"] : ""}><input disabled={!possibleCharSkillProf.includes(sk.name) || char.skillProfLeft <= 0} checked={charSkills.includes(sk.name)} onChange={() => chooseSkill(sk.name)} type='checkbox' name={sk.name} /> <div className={styles["skill__ab"]}> {sk.ab.toUpperCase()} </div> <div className={styles["skill__name"]}>{sk.name} </div>  </label>)}
        </form>
    </>
}

// src/app/components/character/skills/skills.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-skills',
  templateUrl: './skills.component.html',
  styleUrls: ['./skills.component.scss']
})
export class SkillsComponent implements OnInit {
  @Input() char!: ApiResp<Character>
  possibleCharSkillProf: string[] = []
  charSkill: string[] = []
  constructor() {}

  ngOnInit(): void {
    this.possibleCharSkillProf = this.char.char.Class.skillProf.map(sk => sk.name)
    this.charSkill = this.char.char.Skills.map(sk => sk.name)

  }

}

<form class="skill__form" *ngIf="char">
  <span *ngIf="char.char.skillProfLeft > 0">You still have {{char.char.skillProfLeft}} skills to add to your
    profs</span>

  <label *ngFor="let skill of char.skills" [ngClass]="{
    'skill__prof--blue': charSkill && charSkill.includes(skill.name)

  }">
    <input [disabled]="!possibleCharSkillProf.includes(skill.name) || char.char.skillProfLeft <=0"
      [checked]="charSkill && charSkill.includes(skill.name)" type="checkbox" [name]="skill.name" />
    <div class="skill__ab--blue">
      {{skill.ab.toUpperCase()}}
    </div>
    <div class="skill__name">{{skill.name}} </div>
  </label>
</form>
