// src/app/components/Input/BubbleInput/BubbleInput.tsx
import { RootState, useAppDispatch, useAppSelector } from "../../../redux"
import Input from "../Input"
import styles from "../Input.module.scss"
interface InputProps {
    side: "left" | "right"
    name: string
    type: string | false
    defaultVal?: string
    disabled?: boolean
    className?: string
    style?: Object
    hasSubBubble?: boolean
    color: "pink" | "green" | "blue" | "orange"
    labelVal?: string
    subBubbleVal?: string
}

export const BubbleInput: React.FC<InputProps> = ({
    side,
    name,
    defaultVal,
    type,
    disabled,
    className,
    style,
    hasSubBubble = false,
    labelVal = name,
    subBubbleVal,
    color,
}) => {
    const asyncDispatch = useAppDispatch()
    const edit = useAppSelector((state: RootState) => state.character.editMode)

    return (
        <div className="bubble__form">
            <Input
                color={color}
                name={name}
                type={type}
                defaultVal={defaultVal}
                disabled={disabled}
                style={{ [side]: "0px" }}
                className={`${styles["bubble__input"]}`}
            />

            <div
                className={`${styles["bubble__text"]} ${styles[`char__banner--${color}`]
                    }`}
                style={{ textAlign: side === "left" ? "center" : "start" }}
            >
                {labelVal}
            </div>

            {(!edit && hasSubBubble) && (
                <div className={`${styles["sub__bubble"]} ${styles[`char__banner--${color}`]}`}>
                    {subBubbleVal}
                </div>
            )}
        </div>
    )
}

// src/app/components/layout/bubble-input/bubble-input.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-bubble-input',
  templateUrl: './bubble-input.component.html',
  styleUrls: ['./bubble-input.component.scss']
})
export class BubbleInputComponent implements OnInit {
  @Input() side!:"left" | 'right'
  @Input() color!: Colors
  @Input() defaultValue!: string
  @Input() disabled: boolean = false
  @Input() type:string = "text"
  @Input() placeholder!: string
  @Input() id!: string
  @Input() name!: string
  @Input() label!:string
  constructor() { }

  ngOnInit(): void {
  }

}

<div class="bubble__form">
  <app-input [color]="color" [name]="name" [type]="'type'" [defaultValue]="defaultValue" [disabled]="disabled"
    [ngStyle]="{
      'left': side === 'left' ? '0px' : 'unset',
      'right': side === 'right' ? '0px' : 'unset'
    }" class="bubble__input"></app-input>

  <div class="bubble__text" [ngClass]="{
    'custom__input--blue': color === 'blue',
    'custom__input--green': color === 'green',
    'custom__input--pink': color === 'pink',
    'custom__input--orange': color === 'orange'
  }" [ngStyle]="{
    textAlign: side === 'left' ? 'right' : 'left'
  }">
    {{label}}
  </div>


</div>
