// src/app/components/Select/Select.tsx
import { FC, useState } from "react";
import "./Select.scss";
interface SelectProps {
  options: Array<Option>;
  field: string
  // value: Option
}
export class OptionClass implements Option {
  val: string
  display: string
  constructor(val: string, display: string) {
    this.val = val
    this.display = display
  }
}
const Select: FC<SelectProps> = ({ options,  field }) => {
  const [selected, setSelected] = useState<Option | undefined>(undefined);
  const [open, setOpen] = useState<boolean>(false);
  return (
    <div className="select">
      <div className="select__wrap" onClick={() => setOpen(!open)}>
        <strong>{selected?.display || "Select one"}</strong>
      </div>
      {open && (
        <div className="select__options">
          {options.map((opt, i) => (
            <div
              key={`race_${opt.display}_${i}`}
              className="single-option"
              onClick={(ev) => {
                setSelected(opt); //set selection in this component
                setOpen(false); //closes component
              }}
            >
              {opt.display}
            </div>
          ))}
        </div>
      )}
      <select name={field} style={{ display: "none" }} value={selected ? selected.val : selected } >
        {options.map((opt,i) => (
          <option
            key={`select_${opt.display}_${i}`}
            value={opt.val}
          >
            {opt.display}
          </option>
        ))}
      </select>
    </div>
  );
};
export default Select;

// src/app/components/layout/select/select.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-select',
  templateUrl: './select.component.html',
  styleUrls: ['./select.component.scss']
})
export class SelectComponent implements OnInit {
  open: boolean = false
  selected!: Option
  @Input() options!: Option[];
  @Input() field!: string
  constructor() { }

  ngOnInit(): void {
  }

  setOpen(val:boolean) {
this.open = val
  }

  setSelected(opt:Option) {
    this.selected = opt
  }

  select(opt: Option) {
    this.setSelected(opt); //set selection in this component
    this.setOpen(false); //closes component

  }
}

<div class="select">
  <div class="select__wrap" (click)="setOpen(!open)">
    <strong>{{selected?.display || "Select one"}}</strong>
  </div>
    <div class="select__options" *ngIf="open">
        <div *ngFor="let opt of options"
          class="single-option"
          (click)="select(opt)"
        >
          {{opt.display}}
        </div>
    </div>
  <select [name]="field" style="display:none" [value]="selected ? selected.val : selected" >
      <option *ngFor="let opt of options"
        [value]="opt.val"
      >
        {{opt.display}}
      </option>
  </select>
</div>
