// src/app/views/Dashboard/Dashboard.tsx
import { useState } from "react";
import CreateNew from "../../components/CreateNew/CreateNew";
import Jumbotron from "../../components/Jumbotron/Jumbotron";
import Modal from "../../components/Modal/Modal";

import "./Dashboard.scss";

const Dashboard = () => {
  const [showJumbo, setShowJumbo] = useState<boolean>(true)
  const [showModal, setShowModal] = useState<boolean>(false)
  return <div className="dash__wrap">
    {/* {showJumbo && <Jumbotron show={(data:Boolean)=> setShowJumbo(data)}/>} */}
    <CreateNew show={()=>setShowModal(true)}/>
    {showModal && <Modal close={()=>setShowModal(false)} />}
  </div>;
};
export default Dashboard;

// src/app/pages/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CharactersService } from 'src/app/services/characters.service';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {
  chars!: Character[]
  constructor(private charSrv:CharactersService) {
    this.charSrv.getAllChars().subscribe(res => {
      this.chars = res
    })
  }

  ngOnInit(): void {
  }

}

<div class="dash__wrap">
  <!-- {/* {showJumbo && <Jumbotron show={(data:Boolean)=> setShowJumbo(data)}/>} */}

  <CreateNew show={() => setShowModal(true)} />

    {chars.map((char) => {
    return <SingleChar char={char} />
  })}
  {showModal && <Modal close={() => setShowModal(false)} />} -->
  <app-single-char *ngFor="let char of chars" [char]="char"></app-single-char>
</div>
